const datos = [
    {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Ferritina",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0301026",
        nota: "Resultado en la tarde",
      },
      {
        examen: "Baciloscopía",
        establecimiento: "No se realiza, elegir <b>PCR-RT Tuberculosis (TBC)</b>",
        nota: "Plan Nacional de TBC dejó de hacer baciloscopías, solo PCR y Cultivo",
      },
      {
        tubo: "<img src='img/forina32.png' height='32px'/>",
        examen: "PCR-RT Tuberculosis (TBC)",
        keywords: ['baciloscopia', 'mycoplasma tuberculosis'],
        establecimiento: "<img src='img/ispchs32.png' width='20'/> Hospital",
        codigo: "",
        nota: "<i>Mycoplasma tuberculosis</i><br>Cultivo y Baciloscopía para TBC, se envía con solicitud de PCR al Hospital",
      },
      {
        tubo: "<img src='img/forina32.png' height='32px'/>",
        examen: "Cultivo Tuberculosis (TBC)",
        keywords: ['baciloscopia', 'mycoplasma tuberculosis'],
        establecimiento: "<img src='img/ispchs32.png' width='20'/> Hospital",
        codigo: "",
        nota: "Se envía con solicitud de PCR-RT Tuberculosis (TBC)",
      },
      {
        examen: "Interferon Gamma (IGRA)",
        keywords: ['quantiferon',],
        establecimiento: "No se realiza<br>No se deriva",
        codigo: "",
        nota: "Quantiferon",
      },
      {
        examen: "Reacción de la Tuberculina (PPD) ",
        keywords: ['intradermorreaccion', 'aspergilina', 'histoplasmina'],
        establecimiento: "No se realiza<br>No se deriva",
        codigo: "",
        nota: "",
      },
      {
        examen: "Células de Lupus",
        establecimiento: "No se realiza<br>No se deriva",
        codigo: "",
        nota: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Índice Androgénico Libre",
        establecimiento: "<img src='img/bk.png' /> Barnafi",
        codigo: "0303123",
        codigoBK: "IAL",
        nota: "Incluye determinación de SHBG + Testosterona total",
      },
      {
        tubo: "<img src='img/tstuart32.png' height='32px'/>",
        examen: "Secreción Uretral",
        keywords: ['gonococo', 'neisseria gonorrhoeae'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0308044",
        nota: "Estudio de <i>Neisseria gonorrhoeae</i><br>Sin aseo, toma de muestra uretral + Orina de primer chorro.",
      },
      {
        tubo: "<img src='img/tstuart32.png' height='32px'/>",
        examen: "Cultivo Gonococo (mujer)",
        keywords: ['gonococo', 'neisseria gonorrhoeae'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0308016",
        nota: "Toma de muestra por profesional médico",
      },
      {
        tubo: "<img src='img/tstuart32.png' height='32px'/>",
        examen: "Flujo Vaginal",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0308044-1",
        nota: "Muestra tomada por la paciente o profesional",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Estudio de Líquido Sinovial (Articular)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0308014",
        nota: "Estudio completo:<br><ol><li>Frasco esteril: Microbiología<li>Tubo Lila: Citología<li>Tubo Rojo: Bioquímica ",
        img: "<ol><li><img src='img/forina32.png' height='32px'/><li><img src='img/tlila32.png' height='32px'/><li><img src='img/trojo32.png' height='32px'/>"
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Hemograma",
        keywords: ['recuento', 'leucocitos', 'eritrocitos', 'plaquetas', 'VHS', 'hto', 'hematocrito', 'hb', 'hemoglobina' ],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0301045",
        nota: "<ol><li>Rto. Leucocitos<li>Rto. Eritrocitos<li>Rto. Plaquetas<li>Hemoglobina<li>Hematocrito<li>VHS<li>Indices corpusculares<li>Formula diferencial</ol>"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Espermiograma",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0308029",
        nota: "Datos necesarios:<ol><li>Hora toma de muestra<li>Días de abstinencia (3 min.)<li>Vasectomía<li>Pegar etiqueta en papel de datos"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Proteína C Reactiva (PCR)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305031",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Inmunoglobulina A Total (IgA)",
        keywords: ["iga total"],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305027-1",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Inmunoglobulina G Total (IgG)",
        keywords: ["igg total"],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305027-2",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Inmunoglobulina M Total (IgM)",
        keywords: ["igm total"],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305027-3",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Inmunoglobulina E Total (IgE)",
        keywords: ["ige total"],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305028",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Imunoglobulinas Totales (IgA, IgM, IgG)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305027",
        nota: "Cobro x3",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Globulinas Totales (Proteínas + Albúmina)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302100<br>0302101",
        nota: "<u>Ingresar ambos códigos</u><br>Proteínas Totales: 0302100<br>Albumina: 0302101",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Leucocitos Fecales",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Sangre Oculta en Deposición (FOB)",
        keywords: ['Test inmunologico en deposicion'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "(Test inmunológico en deposición)"
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Antígeno Helicobacter pylori en Deposición",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "<b>Cod. MK:</b> 8003250<br>",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Rotavirus / Adenovirus en Deposición",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Clostridioides difficile, GDH Toxina A y B",
        keywords: ['clostridium'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Antes: Clostridium difficile"
      },
      {
        examen: "Panel Viral (8 Virus Respiratorios)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "IFI/IFD Para Virus Influenza A+B, VRS, ADV, MPV, Parainfluenza 1, 2 y 3.",
      },
      {
        tubo: "<img src='img/tstuart32.png' height='32px'/>",
        examen: "Chlamydia trachomatis ",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Mujer: Flujo vaginal<br>Hombre: Orina",
        img: "<img src='img/tstuart32.png' height='32px'/><br><img src='img/forina32.png' height='24px'/>"
      }, 
      {
        examen: "Neonatal GSS (TSH Recién Nacido)",
        keywords: ['tiroestimulante', 'TSH', 'tiroidea',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302097",
        codigoBK: "TSHN",
        nota: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hormona Estimulante de la Tiroides (TSH)",
        keywords: ['tiroestimulante', 'TSH', 'tiroidea',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0303024",
        nota: "Hormona Tiroidea/Tiroestimulate"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Orina Completa",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        examen: "Perfil de Aminoácidos y Acilcarnitinas",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302098",
        codigoBK: "ACILPLUS",
        nota: "Muestra: Gotas de sangre total sobre papel filtro especial",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Perfil Lipídico",
        keywords: ['Colesterol','LDL','HD','Trigliceridos'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "<ol><li>Colesterol Total<li>LDL<li>HDL<li>Trigliceridos",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Perfil Bioquímico",
        keywords: ['Bilirrubina','ALP','AST', 'GOT', 'LDH','Glicemia','glucosa','Urea','BUN','Calcio','Fosforo','Colesterol','Proteinas','Albumina','acido Urico',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "<ol><li>Bilirrubina Total<li>ALP<li>AST/GOT<li>LDH<li>Glicemia<li>Urea/BUN<li>Calcio<li>Fosforo<li>Colesterol Total<li>Proteínas Totales<li>Albúmina<li>Fracción A/G<li>Ácido Urico",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Perfil Hepático",
        keywords: ['Bilirrubina','ALP','ALT','GPT','AST','GOT','GGT', 'protrombina', 'tp'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "<ol><li>Bilirrubina Total<li>Bilirrubina Directa<li>ALP<li>ALT/GPT<li>AST/GOT<li>GGT<li>Protrombina",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Fierro sérico (Hierro)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Capacidad Total de Fijación del Hierro (TIBC)",
        keywords: ['saturación'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0301029"
        
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Fierro con Saturación de Transferrina (Porcentaje)",
        keywords: ['Indice de saturación de transferrina', 'TIBC', 'capacidad total de fijacion del hierro'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0301029",
        nota: "Incluye Capacidad Total de Fijación del Hierro (TIBC) y Fierro Sérico",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Grupo Sanguíneo (ABO, Rh-D)",
        keywords: ['Grupo y rh'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Hemoglobina glicosilada (HbA1c)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Recuento de Reticulocitos",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Test de Coombs Indirecto (TCI)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Test de Coombs Directo (TCD)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/tcel32.png' height='32px'/>",
        examen: "Tiempo de Protrombina (TP)",
        keywords: ['porcentaje de protrombina', 'tiempos de coagulacion', 'coagulacion', 'inr'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "<ol><li>Tiempo<li>Porcentaje<li>INR</ol>"
      },
      {
        tubo: "<img src='img/tcel32.png' height='32px'/>",
        examen: "Tiempo de Tromboplastina Activada (TTPA)",
        keywords: ['coagulacion', 'TTPK',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Antiguamente TTPK",
      },
      {
        tubo: "<img src='img/tmed32.png' height='18px'/>",
        examen: "Tiempo de sangría",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Evaluación de la Hemostasia Primaria en el reclutamiento y activación plaquetaria",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Transferrina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0301082",
        codigoBK: "TRANS",
        nota: "Muestra: Suero, 1 mL<br>Proteína transportadora de hierro (cuantificación)",
      },    
      {
        tubo: "<img src='img/ccrea.png' height='32px'/>",
        examen: "Clearence de Creatinina",
        keywords: ["depuración de creatinina", "aclaramiento de crea"],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302024",
        nota: "Indicar:<ul><li>Estatura<li>Peso Kg</li></ul>Examen calculado con:<ol><li>Creatininuria 24h<li>Creatinina en sangre</li></ol>Muestras:<ol><li>Orina 24 h.<li>Suero"
      },
      {
        tubo: "<img src='img/tcel32.png' height='32px'/>",
        examen: "Dimero D",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Tubo celéste: Sangre citratada"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Electrolitos plasmáticos (ELP)",
        keywords: ['ionograma', 'sodio', 'potasio', 'cloro'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0308012 (x3)",
        nota: "Sodio (Na), Potasio (K) y Cloro (Cl).",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Procalcitonina",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/tverde32.png' height='32px'/>",
        examen: "Péptido Natriurético tipo B (NT-proBNP)",
        keywords: ['pro bnp',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Tubo verde: Sangre heparinizada",
      },
      {
        tubo: "<img src='img/tverde32.png' height='32px'/>",
        examen: "Troponina",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Tubo verde: Sangre heparinizada"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Vitamina B12 (Cobalamina)",
        keywords: ['vit b12', 'vit12'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Vitamina D (25-Hidroxivitamina D)",
        keywords: ['vitd', 'vit d', '25 oh'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302078",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Antígeno Prostatico Especifico (APE Total)",
        keywords: ['PSA'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Total Prostatic Specific Antigen (PSA Total)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Antígeno Prostatico Especifico Libre (APE Libre)",
        keywords: ['free PSA', 'psa'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        nota: "Free Prostatic Specific Antigen (PSA Libre)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Antitiroglobulina (ATG)",
        keywords: ['ac antitiroglobulina', 'ac tg'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305007-2",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti-Tiroperoxidasa (ATPO)",
        keywords: ['ac antitiroperoxidasa', 'anti tpo', 'tpo', 'antiperoxidasa'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305007-3"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Tiroideos (ATG-TPO)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305007",
        nota: "Determinación de ATG y ATPO.<br>Cobro 0305007 x2"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Antígeno Carcinoembrionario (CEA)",
        keywords: ['ACE','tumoral', 'ag carcino'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305009",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Complemento C3 y C4",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "IgA Secretora",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305026"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hantavirus (IgM)",
        keywords: ['virus hanta'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0306121"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Hepatitis B (HBsAg)",
        keywords: ['VHB', 'superficie'],
        establecimiento: "<img src='img/adv.png' /> Clinala - <img src='img/ispchs32.png' width='20'/> ISPCH",
        codigo: "0306079",
        nota: "Antígeno de superficie de Hepatitis B",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Mycoplasma pneumoniae IgM+IgG",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0306037",
        nota: "Se cobra por dos determinaciones (IgM e IgG)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Mycoplasma pneumoniae IgM",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0306037-1",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Mycoplasma pneumoniae IgG",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0306037-2",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Virus Inmunodeficiencia Humana (VIH SIDA)",
        establecimiento: "<img src='img/adv.png' /> Clinala - <img src='img/ispchs32.png' width='20'/> ISPCH",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Hepatitis C (VHC)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306081",
        nota: "Solo si tiene otros exámenes a barnafi, de lo contrario: Lab. Cordillera",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Hepatitis A (VHA IgM)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306074",
        codigoBK: "HAV",
        nota: "Diagnóstico de infección VHA"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Hepatitis A, Anticuerpos totales (IgG, IgM)",
        keywords: ['vha', 'anticuerpos hepatitis a'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306074",
        codigoBK: "HAVG",
        nota: "Memoria inmunológica"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Linfotrópico Humano, tipo I y II (HTLV)",
        keywords: ['htlv1', 'htlv2'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306111",
        codigoBK: "HTLV", 
        nota: "Anticuerpos IgG-IgM-IgA contra HTLV I y HTLV II<br>En caso de reactividad, Bklab solicitará nueva muestra con EDTA para envío a ISPCH.",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Calprotectina",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Gonadotropina Corionica Humana, subunidad beta (BHCG)",
        keywords: ['embarazo', 'B-HCG'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Insulina",
        keywords: ['resistencia'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Insulina Post Prandial",
        keywords: ['resistencia'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Curva de Insulina (3 muestras)",
        keywords: ['resistencia'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Estradiol (Estrógenos)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0303030",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hormona Foliculo Estimulante (FSH)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0303015",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hormona Leutinizante (LH)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0303016",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Prolactina",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Pool de Prolactina",
        keywords: ['Pool Prolactina'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Proteinuria",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        examen: "Proteinuria 24h",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Ratio microalbuminuria (RAC)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Microalbuminuria",
        keywords: ['ualb',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        examen: "Microalbuminuria 24h",
        keywords: ['ualb 24',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Ácido Fólico",
        keywords: ['Ac Folico', 'Ac. Folico', 'folatos'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0301002",
        codigoBK: "FOL", 
        nota: "Muestra: Suero o Plasma, 500 ul",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Ácido Fólico Eritrocitario",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "FOLERI",
        nota: "<b>Cod. MK:</b> 8003631"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Adenosindeaminasa (ADA)",
        keywords: ['deaminase',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "ADDA",
        nota: "<b>Cod. MK:</b> 8003428<br>Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Caroteno",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302017",
        codigoBK: "CARO"
      },
      {
        examen: "Caroteno, Prueba de Sobrecarga",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302018",
        codigoBK: ""
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Calcio en orina",
        keywords: ['calciuria', 'calcio orina', 'ca orina'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0309008",
        nota: "Calciuria"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Uricosuria",
        keywords: ['ac urico',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0309004",
        nota: "Ácido Úrico en orina aislada"
      },
      {
        examen: "Uricosuria 24h",
        keywords: ['ac urico 24h',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0309004-1",
        nota: "Ácido Úrico en orina de 24"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Fosforo en orina",
        keywords: ['fosfaturia', 'fosforo orina',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0309015",
        nota: "Fosfaturia"
      },
      {
        examen: "Fosforo en orina 24h",
        keywords: ['fosfaturia 24', 'fosforo orina 24',],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0309015-1",
        nota: "Fosfaturia en 24 h"
      },
      {
        examen: "Calcio en orina 24h",
        keywords: ['calciuria 24h', 'calcio orina', 'calcio 24', 'ca 24'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0309008-1",
        nota: "Calciuria en 24 horas"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Citrato en orina 24h",
        keywords: ['citraturia 24h', 'citrato orina', 'citrato 24'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0309008-1",
        codigoBK: "CITRATO",
        nota: "Citraturia en 24 horas"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Oxalato en orina 24h",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0309051",
        codigoBK: "OXALATO",
        nota: "Paciente no deba haber ingerido vitamina C (ácido ascórbico)"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Oxalato en orina aislada",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "OXALATOA",
        nota: "Paciente no deba haber ingerido vitamina C (ácido ascórbico)"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Citrato en orina aislada",
        keywords: ['citraturia', 'citrato orina',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "CITRATOA",
        nota: "Citraturia"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Calcio Ionico",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302081",
        codigoBK: "CAION"
      },
      {
        examen: "Calculo Urinario",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0309009",
        codigoBK: "CALC"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Ceruloplasmina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302019",
        codigoBK: "CER",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Cobre en sangre",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302020",
        codigoBK: "CU",
        nota: "<b>Cod. MK:</b> 8003426"
      },
      {
        tubo: "<img src='img/forina32.png' height='32px'/>",
        examen: "Cobre en orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306036",
        codigoBK: "COBOA",
      },
      {
        tubo: "<img src='img/forina32.png' height='32px'/>",
        examen: "Cobre en orina 24 h",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306036",
        codigoBK: "CUO",
        nota: "Escribir en notas que es de 24 h"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Colinesterasa en suero o plasma",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302021",
        codigoBK: "COLI",
      },
      {
        tubo: "<img src='img/tgris32.png' height='32px'/>",
        examen: "Lactato",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "LAC",
        nota: "Tubo gris: Fluoruro u Oxalato<br>Transporte en frío (2 - 8 °C)"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Deshidrogenasa Láctica c/separación isoenzimas",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Fosfatasas Alcalinas c/separación de isoenzimas",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "ISOFA",
        nota: "<b>Cod. MK:</b> 8003407<br>"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Enzima Convertidora De Angiotensina (ECA)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302033",
        codigoBK: "ECA",
        nota: "<b>Cod. MK:</b> 8003607"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Electroforesis de Proteínas",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0301044",
        codigoBK: "EFP"
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Electroforesis de Hemoglobina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0301044",
        codigoBK: "EFHBG"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Electroforesis de Proteínas en Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "EFPO",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        examen: "Fenilalanina neonatal (PKU)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302082",
        codigoBK: "PKU",
        nota: "Muestra: Gotas de sangre total sobre papel filtro especial",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Homocisteína",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302086",
        codigoBK: "HOMOC",
        nota: "<ol><li>Separar rapidamente el suero de glóbulos rojos<li>Transporte refrigerado"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Litio, nivel plasmático",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302055",
        codigoBK: "LIT",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Magnesio",
        keywords: ['mg', 'mgo'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302056",
        codigoBK: "MG",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Ácido 5 Hidroxindol acético (orina 24h)",
        keywords: ['5 OH indol', 'indol', 'ac 5 hidroxi'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "HIAA",
        nota: "<b>Cod. MK:</b> 8003611<br>Se envía en: Contenedor para orina con Ácido Bórico"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Magnesio en orina",
        keywords: ['mg', 'mgo', 'magensiuria'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302052-1",
        codigoBK: "MGO",
      },
      {
        examen: "Magnesio en orina 24h",
        keywords: ['mg', 'mgo', 'magensiuria'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0302052-2",
        codigoBK: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Ácido Valpróico Total, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302035-1",
        codigoBK: "VALP",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Levetiracetam, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "LEVE",
        nota: "<b>Cod. MK:</b> 8003638<br>Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Ácido Valpróico Libre, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "VALPL",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Fenitoína, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302035-4",
        codigoBK: "FEN",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Carbamazepina Total, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302035-2",
        codigoBK: "CARB",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Benzodiazepinas en Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0309106",
        codigoBK: "BENZ",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Oxcarbazepina, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "OXCAR",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Fenobarbital Total, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302035-5",
        codigoBK: "FEB",
        
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Fenobarbital Libre, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "FEBL",
        nota: "Agregar como <i>Examen Barnafi:</i> 0307099 y escribir en notas",
      },
      {
        examen: "Examen Barnafi",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0307099",
        nota: "Se utiliza cuando no hay indexado un examen y este debe ser referido en notas",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Plomo",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302084",
        codigoBK: "PLOMOMASA",
        nota: "Niveles de plomo en sangre total"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Plomo en Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302084",
        codigoBK: "PLOOA",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Prealbúmina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302085",
        codigoBK: "PREALB",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Triptasa",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305201",
        codigoBK: "TRIPTASA",
        nota: "<b>Cod. MK:</b> 8003620",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Sirolimus, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "SIR",
        codigoBK: "SIR",
        nota: "<b>Cod. MK:</b> 8003636"
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Tacrolimus, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "TAC",
        codigoBK: "TAC",
        nota: "<b>Cod. MK:</b> 8003635",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Vitamina A (Retinol)",
        keywords: ['vit a', 'acido retinoico', 'ac retinoico'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "VITA",
        codigoBK: "VITA",
        nota: "<b>Cod. MK:</b> 8003621<br>Ácido Retinoico"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Vitamina B6 (Piridoxina)",
        keywords: ['vit b6', 'vitb6'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302080",
        codigoBK: "VITB6",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Zinc",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302198",
        codigoBK: "ZN",
        nota: "<b>Cod. MK:</b> 8003615"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Zinc en Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302198",
        codigoBK: "ZINCOA",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "17-Hidroxiprogesterona (17-OHP)",
        keywords: ['17 oh progesterona'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303029",
        codigoBK: "17PR",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti-Membrana Basal Glomerular (AAMBG)",
        keywords: ['ac antimembrana basal'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305081-2",
        codigoBK: "MEMBRA",
        nota: "<b>Cod. MK:</b> 8003624"
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Hormona Adrenocorticotropica (ACTH)",
        keywords: ['corticotropina', 'corticotrofina'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303001",
        codigoBK: "ACTH",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Catecolaminas Plasmáticas",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303049",
        codigoBK: "CATEP",
        nota: "<b>Cod. MK:</b> 8003610",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Catecolaminas en Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303051",
        codigoBK: "CATEOA",
        nota: "<b>Cod. MK:</b> 8003428<br>"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Drogas de Abuso (THC, COC, ANF) c/u",
        keywords: ['marihuana', 'cocaina', 'anfetaminas'], 
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0309105",
        codigoBK: "",
        nota: "<b>Cod. MK:</b> 8003255 c/u<br><ul><li>Marihuana<li>Cocaína<li>Anfetaminas"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Aldosterona",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "303002",
        codigoBK: "ALDO",
        nota: "Requiere Ayuno de 8 h.<br>Paciente debe permanecer sentado 15 minutos antes de la punción.<br>Indicar <i><u>posición: sentado</u></i> en el envío a Barnafi."
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Aldosterona en orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c - Ingresar: 0307099",
        codigoBK: "ALDOO",
        nota: "Escribir en notas: ALDOSTERONA EN ORINA y cobrar con codigo Fonasa: 303002"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Androstenediona (4-androstenediona)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303003",
        codigoBK: "ANDROD",
        nota: "Muestra de Suero EDTA o Heparina"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Parvovirus B19, anticuerpos IgG, IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "IgG: <b>PAVOG</b><br>IgM: <b>PAVOM</b>",
        nota: "<b>Cod. MK:</b> 8003639 x2<br>"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Cortisol AM/PM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303006",
        codigoBK: "CORT",
        nota: "AM: antes de las 10:00 am<br>PM: entre las 16:00 - 16:30 hrs"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Cortisol Libre Urinario",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303035",
        codigoBK: "CORTOA",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Cortisol en Orina 24h",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303035",
        codigoBK: "CORTO",
        nota: "<b>Cod. MK:</b> 8003606<br>"
      },
      {
        examen: "Cortisol en Saliva",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303056",
        codigoBK: "CORTS",
        nota: "Las muestras tienen que congelarse, descongelarse y centrifugarse al menos una vez para separar las mucinas. Luego enviar."
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Dehidroepiandrosterona, sulfato (DHEA-SO4)",
        keywords: ['dheas'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303008",
        codigoBK: "DHEAS",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Gastrina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303012",
          codigoBK: "GAS",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Insulin-Like Growth Factor 1 (IGF1)",
        keywords: ['somatomedina', 'crecimiento', 'similar a insulina', 'factor 1 de crecimiento'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303047",
        codigoBK: "IGF-IQ",
        nota: "Somatomedina, Factor 1 de Crecimiento Similar a Insulina",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Insulin-Like Growth Factor Binding Protein-1 (IGFBP1)",
        keywords: ['proteina 1', 'crecimiento', 'similar a insulina', 'factor de crecimiento', 'ligado a',
          'igf binding', 'igf ligado',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303048",
        codigoBK: "BP1",
        nota: "Proteina 1 de union al Factor de Crecimiento Similar a Insulina, IGF Binding Protein 1",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Insulin-Like Growth Factor Binding Protein-3 (IGFBP3)",
        keywords: ['proteina 3', 'crecimiento', 'similar a insulina', 'factor de crecimiento', 'ligado a',
          'igf binding', 'igf ligado',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303048-1",
        codigoBK: "IGFBP-3Q",
        nota: "Proteina 3 de union al Factor de Crecimiento Similar a Insulina, IGF Binding Protein 1",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Metanefrinas Plasmáticas",
        keywords: ['metanefrinas en sangre',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "METALIBRE",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas<br>s/c Fonasa, cobro particular",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Metanefrinas Urinarias",
        keywords: ['metanefrinas en orina',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303050",
        codigoBK: "METANEF",
        nota: "<b>Cod. MK:</b> 8003431<br>"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Progesterona",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303019",
        codigoBK: "PRGD",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Renina plasmática",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303021",
        codigoBK: "RENINA",
        nota: "<ol><li>Centrifugar inmediatamente<li>Extraer plasma<li>Congelar<li>Transporte congelado"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Sex hormone binding globulin (SHBG)",
        keywords: ['globulina fijadora',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303046",
        codigoBK: "SHBG",
        nota: "Globulina Fijadora de Hormonas Sexuales",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Testosterona Libre",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303023",
        codigoBK: "TESTL",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Testosterona Total",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0303022",
          codigoBK: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Tiroglobulina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303025",
        codigoBK: "TIROG",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Alfa 1 Antitripsina (AAT)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "305001",
        codigoBK: "AATT",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Alfa 2 Macroglobulina (A2M)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305002",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Alfa Feto Proteina (AFP)",
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305003",
        codigoBK: "AFP",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Panel ANA 23 Autoanticuerpos IgG",
        keywords: ['ac antinucleares', 'anticuerpos nucleares', 'ac antinucleares'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305005-5",
        codigoBK: "ANA23",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Antinucleares (ANA)",
        keywords: ['aan', 'ac antinucleares', 'anticuerpos nucleares', 'ac antinucleares', 'anticuerpos anti nucleares'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305005",
        codigoBK: "ANAS",
        nota: "AAN (en inglés), Patrones de Anticuerpos Anti-Nucleo/Citoplasma para detección de autoinmunidad"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti DNA",
        keywords: ['ac anti dna', 'ac anti adn', 'ac anti adn', "antidna", "antiadn"],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305005-3",
        codigoBK: "ADNA",
        nota: "<strong>Código Fonasa:</strong> 0305005<br> Anticuerpos anti ADN nativo de doble cadena (dsDNA)"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Péptido Citrulinado IgG (CCP)",
        keywords: ['anti ccp', 'ac anti ccp', 'anticuerpos anti ccp', 'accp',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305099",
        codigoBK: "CCPP",
        nota: "<b>Cod. MK:</b> 8003407"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Endomisio IgA (EMA)",
        keywords: ['ac anti endomisio', 'antiendomisio'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305081-1",
        codigoBK: "EMA",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Peptido Deaminado de Gliadina IgA ",
        keywords: ['ac anti peptido deaminado de gliadina iga',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305086-1",
        codigoBK: "GLIDA",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Peptido Deaminado de Gliadina IgG ",
        keywords: ['Ac Antifosfolipidos',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305086-2",
        codigoBK: "GLIDG",
      },
    {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Antifosfolipidos",
        keywords: ['ac anti fosfolipidos',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305007-4",
        codigoBK: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Gliadina IgG",
        keywords: ['ac antigliadina igg', 'ac anti gliadina igg',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305086",
        codigoBK: "GLIG",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Gliadina IgA",
        keywords: ['ac antigliadina iga', 'ac anti gliadina iga',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305086",
        codigoBK: "GLIA",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Transglutaminasa IgA",
        keywords: ['ac anti transgluta', 'antitransgluta'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305181-1",
        codigoBK: "GLUTAS",
        
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Transglutaminasa IgG",
        keywords: ['ac anti transgluta', 'antitransgluta'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305181-2",
        codigoBK: "GLUTAG",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Células Parietales (IFI)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "PARI",
        codigoBK: "PARI",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Células Parietales IgG",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "PARIELISA",
        codigoBK: "PARIELISA",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Microsomales",
        keywords: ['antimicrosomales', 'ac antimicroso', 'ac anti micros'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305007-1",
        codigoBK: "AMIC",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Cardiolipinas (IgG y/o IgM)",
        keywords: ['ac Anti Cardiolipinas', 'anticardiolipi',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305084",
          codigoBK: "Para IgG: CARG, Para IgM: CARM",
        nota: "Especificar segun corresponda",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticoagulante Lupico",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigoBK: "LUPI",
        nota: "<b>Cod. MK:</b> 8003424"
        
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Receptor de TSH (TRAB)",
        keywords: ['ac antireceptor', 'antireceptor', 'ac anti receptor', 'anti trab', 'ac anti trab',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305124",
        codigoBK: "TRABB",
        nota: "<b>Cod. MK:</b> 8003625"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti B2 Glicoproteina IgG",
        keywords: ['anti b2', 'ac antiglicoproteina', 'ac anti glicoproteina', 'ac antib2', 'ac anti b2 glicoproteina'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305105",
        codigoBK: "B2G",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti B2 Glicoproteina IgM",
        keywords: ['anti b2', 'ac antiglicoproteina', 'ac anti glicoproteina', 'ac antib2', 'ac anti b2 glicoproteina'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305105-1",
        codigoBK: "B2M",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Musculo liso (AMLI)",
        keywords: ['ac antimusuclo', 'ac anti musculo', 'antimusculo'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305005-4",
        codigoBK: "AMLI",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti LKM-1 (LKM)",
        keywords: ['ac anti lkm', 'anti lkm',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "LKM",
        nota: "<b>Cod. MK:</b> 8003434<br>Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Mitocondriales (AMIT)",
        keywords: ['ac anti mitocondriales', 'anti mitocondriales', 'antimito',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305005-2",
        codigoBK: "AMIT",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Mieloperoxidasa (MPO)",
        keywords: ['ac anti mielopero', 'anti mielopero', 'antimielopero', 'antimpo', 'anti mpo',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305107",
        codigoBK: "MPO",
        nota: "Cuantificación por ELISA de un tipo de anticuerpo ANCA"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anticentromero (ACA)",
        keywords: ['ac anti centromero', 'anti centromero', 'ac anticentromero', 'centromero',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305005-1",
        codigoBK: "ANTICEN",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Proteinasa 3 (ANTI-PR3)",
        keywords: ['ac proteinasa3', 'antiproteinasa',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305007-10",
        codigoBK: "PR3",
        nota: "<b>Cod. MK:</b> 8003634<br>Cuantificación por ELISA de un tipo de anticuerpo ANCA"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anticitoplasma de Neutrofilos (ANCA)",
        keywords: ['ancas'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305082",
        codigoBK: "ANCA",
        nota: "Patones de fluorescencia c-ANCA y p-ANCA.<br> Anticuerpos ANCA reaccionan con antigenos MPO y PR3 presentesn en Neutrofilos "
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anticitoplasma de Neutrofilos C (ANCA C)",
        keywords: ['ancac'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305082",
        codigoBK: "ANCAC",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anticitoplasma de Neutrofilos P (ANCA P)",
        keywords: ['ancap',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305082",
        codigoBK: "ANCAP",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "CA 15-3",
        keywords: ['ca15-3','tumoral'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305170",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "CA 19-9",
        keywords: ['ca19','tumoral'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305170-1",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "CA 125",
        keywords: ['ca125','tumoral'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0305170-2",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti-SM, RNP, LA (SS-B), RO (SS-A), SCL-70, JO-1 C/U",
        keywords: ['anti sm', 'anti RO', ' anti RNP', 'anti LA', 'anti SCL', 'anti JO',
                    'smith', 'ena'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305108",
        codigoBK: "SM, RNP, SB, SA, SCL, JO",
        nota: "La solicitud a BkLab debe ser por c/u de los anticuerpos y su cobro: 0305108 x6 "
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "ENA screening (ENAS)",
        keywords: ['SM', 'RO', 'RNP', 'LA', 'SCL-70', 'JO-1', 'tamizaje'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305004",
        codigoBK: "ENAS",
        nota: "Tamizaje para complejo de antígenos: SM, LA(SS-B), RO(SS-A), RNP, SCL-70, JO-1"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Inmunofijación de Inmunoglobulinas en Sangre",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305025",
        codigoBK: "INMUNOFIJA",
        nota: "<b>Cod. MK:</b> 8003433"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Inmunofijación de Inmunoglobulinas en Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305025-1",
        codigoBK: "INMUNOFIJO",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "IgE Especificas c/u",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305029",
        codigoBK: "IGEE",
        nota: "<button class='btn btn-primary' onclick=\"window.location.href='IgE.html'\">Buscar Alérgenos</button>"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "IgE Especificas, Panel Chile (35 Alérgenos)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305029-1",
        codigoBK: "PCHILE35",
        nota: `
      <button class='btn btn-primary' onclick="
        localStorage.setItem('inputValue', 'Panel Chile, 35 Alérgenos');
        window.location.assign('IgE.html');
      ">Ver Lista</button>
    `
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "IgE Especificas, Panel 22 Alérgenos",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "PANEL22",
        nota: `
      <button class='btn btn-primary' onclick="
        localStorage.setItem('inputValue', 'Panel 22 Alérgenos');
        window.location.assign('IgE.html');
      ">Ver Lista</button>
    `
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Marcadores Inmunologicos en Diabetes",
        keywords: ['tirosin', 'fosfatasa', 'IA2', 'células beta', 'ICA', 'IAA', 'descarboxilasa',
            'acido glutamico', 'gad', 'transportador 8', 'znt8',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305004",
        codigoBK: "APANELDIAS",
        nota: "<b>Código FONASA: 0305106</b><ol>Anticuerpos anti:<li> Tirosin Fosfatasa (IA2),<li> Células beta (ICA),<li> Insulina (IAA),<li> Descarboxilasa del ácido glutámico (GAD),<li> Transportador 8 del Zinc (ZNT8) "
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Células Beta (ICAS)",
        keywords: ['diabetes'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "s/c",
        codigoBK: "ICAS",
        nota: "Ingresar <i>Examen BARNAFI</i>"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Panel Miositis 16, Auto Anticuerpos Tipo IgG",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305007-8",
        codigoBK: "MIOSITIS16",
        nota: "<ol><li>Anti-Mi-2alpha, <li>Anti-Mi-2beta, <li>Anti-TIF1gamma, <li>Anti-MDA5, <li>Anti-NXP2, <li>Anti-SAE1, <li>Anti-Ku, <li>Anti-PM-Scl100, <li>Anti-PM-Scl75, <li>Anti-Jo-1, <li>Anti-SRP, <li>Anti-PL-7, <li>Anti-PL-12, <li>Anti-EJ, <li>Anti-OJ, <li>Anti-Ro52</ol>",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Tipificación HLA-B27",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305118",
        codigoBK: "HLAB27",
        nota: "<b>Cod. MK:</b> 8003601",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Tipificación HLA-DQ2 y HLA-DQ8",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305121",
        codigoBK: "DQ",
        nota: "<b>Cod. MK:</b> 8003685",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hormona Anti Mulleriana (AMH)",
        keywords: ['antimulleriana'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303030-1",
        codigoBK: "MULLE",
        nota: "<b>Cod. MK:</b> 8003626"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Adenovirus Anticuerpos IgG, IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "IgG: ADENG<br>IgM: ADENM",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Antígeno Galactomanano de Aspergillus",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "GALACTO",
        nota: "<b>Cod. MK:</b> 8003612<br>Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas<br>Suero o lavado broncoalveolar",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Bartonella henselae Serología IgG, IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "BARTH",
        codigoBK: "IgG: <strong>BARG</strong><br> IgM: <strong>BARM</strong>",
        nota: "<b>Cod. MK:</b> 8003629<br>Especificar si se requiere uno o ambos anticuerpos con sus codigos BK."
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Chlamydia pneumoniae Serología IgG, IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "IgG: <b>CLANEG</b><br>IgM: <b>CALNEM</b>",
        nota: "Especificar si se requiere uno o ambos anticuerpos con sus codigos BK."

        
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Citomegalovirus (CMV) Serología IgG, IgM ",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306069-3",
        codigoBK: "IgG: <strong>CIG</strong><br> IgM: <strong>CIM</strong>",
        nota: "Especificar si se requiere uno o ambos anticuerpos con sus codigos BK."
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Varicela Zoster, Serología IgG, IgM ",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "IgG: <strong>VARG</strong><br> IgM: <strong>VARM</strong>",
        nota: "<b>Cod. MK:</b> 8003436<br>Especificar si se requiere uno o ambos anticuerpos con sus codigos BK."
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Epstein Barr Virus Serología IgG, IgM ",
        keywords: ['Virus Epstein Barr', 'mononucleosis'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306069-5",
        codigoBK: "IgG: <strong>EBG</strong><br> IgM: <strong>EBM</strong>",
        nota: "Especificar si se requiere uno o ambos anticuerpos con sus codigos BK."
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "FTA-ABS (Sífilis)",
        keywords: ['MHA-TP', 'treponema pallidum'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306041",
        codigoBK: "FTA",
        nota: "<b>Cod. MK:</b> 8003435<br>Anticuerpos anti <i>T. pallidum</i> para diagnóstico de sífilis",
      },
      {
        examen: "MHA-TP (Sífilis)",
        establecimiento: "No se realiza, elegir y sugerir: <strong>FTA-ABS</strong>",
        codigo: "s/c",
        codigoBK: "s/c",
        nota: "Anticuerpos confirmatorios para sífilis, MHA-TP y FTA-ABS",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Herpes Simple I Serología IgG, IgM",
        keywords: ['herpes 1',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306069-1",
        codigoBK: "IgG: <strong>H1G</strong><br> IgM: <strong>H1M</strong>",
        nota: "Especificar si se requiere uno o ambos anticuerpos con sus codigos BK."
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Herpes Simple II Serología IgG, IgM",
        keywords: ['herpes 2',],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306069-2",
        codigoBK: "IgG: <strong>H2G</strong><br> IgM: <strong>H2M</strong>",
        nota: "Especificar si se requiere uno o ambos anticuerpos con sus codigos BK."
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hepatitis B, Anticuerpos Anti-antígeno de superficie (VACUNA)",
        keywords: ['ac anti antigeno', 'anti hepatitis b', 'vhb', 'hepatitis b vacuna'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "ANTIHBS",
        codigoBK: "ANTIHBS",
        nota: "<b>Cod. MK:</b> 8003630<br>Examen para ver inmunidad post <b>vacuna</b>",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hepatitis B, Anticuerpos Anti-Core (IgM)",
        keywords: ['anticore', 'ac anticore', 'vhb'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306080",
        codigoBK: "HEV",
        nota: "Evaluación etapa aguda VHB",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hepatitis B, Anticuerpos Anti-Core Totales (IgG+IgM)",
        keywords: ['anticore', 'ac anticore', 'vhb'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306080",
        codigoBK: "HBC",
        nota: "Evaluación de la memoria inmunológica",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hepatitis B, Antígeno E",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306078",
        codigoBK: "HBE",
        nota: "<b>Cod. MK:</b> 8003437<br>Indicador de infección activa y replicación viral",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Hepatitis B, Anticuerpos Anti-antígeno E",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306075",
        codigoBK: "ANTIHBE",
        nota: "Indicador de infección activa y replicación viral",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "17-Cetosteroides Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303043",
        codigoBK: "",
        nota: "<b>Cod. MK:</b> 8003441<br>"
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "17-Hidroxicorticosteroides",
        keywords: ['17 oh corticosteroides'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303044",
        codigoBK: "",
        nota: "<b>Cod. MK:</b> 8003442<br>Orina de 24 h"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Zika Serología IgG, IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "sin codigo, ingresar Examen barnafi",
        codigoBK: "IgG: <strong>ZIKAG</strong><br> IgM: <strong>ZIKAM</strong>",
        nota: "<b>Cod. MK:</b> 8003614<br>Especificar si se requiere uno o ambos anticuerpos con sus codigos BK.",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Bordetella pertusis IgG",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "BOG",
        codigoBK: "BOG",
        nota: "<b>Cod. MK:</b> 8003628"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Bordetella pertusis IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "BOM",
        codigoBK: "BOM",
        nota: "<b>Cod. MK:</b> 8003628"
      },
      {
        tubo: "<img src='img/trosa.png' height='32px'/>",
        examen: "Panel de Infecciones de Transmision Sexual, 6 Antígenos (PCR-RT)",
        keywords: ['ITS', 'panelits', 'panel its','ETS', 'panel enfermedades de transmision', 'enfermedades de transmision'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306097",
        codigoBK: "PANELSTI",
        nota: "Panel ITS por PCR:<ol><li><i>Chlamydia trachomatis</i><li><i>Mycoplasma genitalum</i><li><i>Mycoplasma hominis</i><li><i>Neisseria gonorrhoeae</i><li><i>Ureaplasma spp.</i><li><i>Trichomonas vaginalis</i><br><b>Mujer:</b> Tubo rosado, tomado por profesional.<br><b>Hombre:</b> Frasco de orina (primer chorro)",
        img: "<img src='img/trosa.png' height='150px'>",
      },
    {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Cadenas Livianas Libres, razon kappa/lambda",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305300",
        codigoBK: "CUANTIKALA",
      },
      {
        tubo: "<img src='img/rcm.png' height='32px'/>",
        examen: "Virus Papiloma Humano PCR-RT (VPH 14 subtipos) MUJER",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306123",
        codigoBK: "HPV",
        nota: "Frasco y Cepillo Citoliq<br><i>Toma de muestra</i>: por profesional médico o matrona.",
        img: "<img src='img/rcm.png'  height='150px'>",
      },
      {
        tubo: "<img src='img/trosa.png' height='32px'/>",
        examen: "Virus Papiloma Humano PCR-Microarray (VPH 30 subtipos) Hombre o Mujer",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306123-1",
        codigoBK: "PCRPAPI",
        nota: "<i>Se cobra particular.</i><br>Tubo rosado con tórula de dacron.<i>Toma de muestra</i>:",
        img: "<img src='img/trosa.png' height='150px'>",     
      },
      {
        examen: "ONCOGEN: Estudio Genético Oncológico",
        establecimiento: "<img src='img/bk.png' /> Barnafi",
        codigo: "ONC",
        codigoBK: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Anticuerpos Anti Receptores de Acetilcolina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "ACERTILRECE",
        codigoBK: "ACETILRECE",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Apolipoproteina A1",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302070-1",
        codigoBK: "APOA",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Apolipoproteina B",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302070-2",
        codigoBK: "APOB",
      },
      {
        tubo: "<img src='img/forina32.png' height='24px'/>",
        examen: "Arsénico en Orina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0309034",
        codigoBK: "ARSOA",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Arsénico en sangre",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302134",
        codigoBK: "ARSESANGRE",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Beta 2 Microglobulina",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0305010",
        codigoBK: "BETA2",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Parathormona (PTH)",
        keywords: ['hormona', 'pth', 'paratiroidea', 'parato'],
        establecimiento: "<img src='img/adv.png' /> Clinala",
        codigo: "0303018",
        codigoBK: "PTHC",
        nota: "Hormona Paratiroidea"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Toxocara IgG",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306061-6",
        codigoBK: "TOXO",
        nota: "Serología IgG para <i>Toxocara canis</i>",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Toxoplasmosis Anticuerpos IgG",
        keywords: ['toxoplasma igg'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306061-7",
        codigoBK: "TOXOG",
        nota: "Serología IgG para Toxoplasma",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Toxoplasmosis Anticuerpos IgM",
        keywords: ['toxoplasma igm'],
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306061-8",
        codigoBK: "TOXOM",
        nota: "Serología IgM para Toxoplasma",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Peptido C",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "303052",
        codigoBK: "PEPC",
        nota: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Lamotrigina, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "LAMO",
        codigoBK: "LAMO",
        nota: "<b>Cod. MK:</b> 8003637"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Parotiditis IgG",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "PARAG",
        codigoBK: "PARAG",
        nota: "<b>Cod. MK:</b> 8003603",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Virus Parotiditis IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "PARAM",
        codigoBK: "PARAM",
        nota: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Subclases de IgG (I, II, III, IV)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "SUBIGG",
        codigoBK: "SUBIGG",
        nota: "Incluye Clases IgG1, IgG2, IgG3 e IgG4 (Sin cod. Fonasa)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Subclase de IgG 1",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "IGG1",
        codigoBK: "IGG1",
        nota: "(Sin cod. Fonasa)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Subclase de IgG 2",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "IGG2",
        codigoBK: "IGG2",
        nota: "(Sin cod. Fonasa)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Subclase de IgG 3",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "IGG3",
        codigoBK: "IGG3",
        nota: "(Sin cod. Fonasa)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Subclase de IgG 4",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "IGG4",
        codigoBK: "IGG4",
        nota: "(Sin cod. Fonasa)",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Triquinosis, Anticuerpos IgG",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306061-5",
        codigoBK: "TRIQ",
        nota: "<i>Trichinella spiralis</i>",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Test Genético de Intolerancia a la Lactosa (PCR-RT)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "8003687",
        codigoBK: "LACTOGEN",
        nota: "Sangre total EDTA, Tubo Lila"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Teofilina, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302035-7",
        codigoBK: "TEO",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Triyodotironina 3 Libre (T3 Libre)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0303057",
        codigoBK: "T3L",
        nota: "T3 Total se hace en Clinala."
      },
      {
        examen: "Streptococcus Grupo B por PCR-RT",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306299",
        codigoBK: "PCRSTREP",
        nota: "<i>Streptococcus agalactiae</i> (Grupo B) por PCR - Biología Molecular<br>Tubo ENAT, Transporte refrigerado"
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Rubeola IgG, IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306069-4",
        codigoBK: "IgG: <strong>RUG</strong><br> IgM: <strong>RUM</strong>",
        nota: "Especificar si se requiere uno o ambos anticuerpos con sus codigos BK.",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Sarampión IgG, IgM",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0306069-6",
        codigoBK: "IgG: <strong>SARG</strong><br> IgM: <strong>SARM</strong>",
        nota: "Especificar si se requiere uno o ambos anticuerpos con sus codigos BK.",
      },
      {
        tubo: "<img src='img/tlila32.png' height='32px'/>",
        examen: "Selenio en sangre",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302135",
        codigoBK: "SELESANGRE",
        nota: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Primidona, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "0302035-6",
        codigoBK: "PRI",
        nota: "",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Primidona libre, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "PRIL",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Ácido Acetilsalicílico, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "SALICIL",
        nota: "Aspirina.<br>Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Ácido Micofenólico, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "MICO",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Alprazolam, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "ALPRA",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        tubo: "<img src='img/trojo32.png' height='32px'/>",
        examen: "Citalopram, nivel plasmático (Fármaco)",
        establecimiento: "<img src='img/bk.png' /> Barnafi (1 semana)",
        codigo: "s/c",
        codigoBK: "CITA",
        nota: "Agregar como <i>Examen Barnafi</i>: 0307099 y escribir en notas",
      },
      {
        examen: "Hepatitis E (no se realiza)",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Panel Gastroenteritis Viral (PCR-RT)",
        establecimiento: "<img src='img/bk.png' /> Barnafi",
        codigo: "0303120<br>(Fonasa)",
        codigoBK: "PCRVIGAS",
        nota: "<ol><li>Norovirus G1<li>Norovirus G2<li>Astrovirus<li>Rotavirus<li>Adenovirus<li>Sapovirus",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Panel Gastroenteritis Bacteriano (PCR-RT)",
        establecimiento: "<img src='img/bk.png' /> Barnafi",
        codigo: "Tecnigen:<ul><li>0303120-1</ul><br>MK:<ul><li>8003451",
        codigoBK: "PCRBAGAS",
        nota: "<ol><li><i>Campylobacter spp.<li><i>Clostridiodes difficile<li><i>E. coli verotixina</li><li><i>E. coli Enteroinvasiva<li><i>Salmonella spp.<li><i>Shigella spp.<li>Yersinia enterocolitica",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Panel Gastroenteritis BACTERIANO - VIRAL (PCR-RT)",
        establecimiento: "<img src='img/bk.png' /> Barnafi",
        codigo: "Tecnigen:<ul><li>0303120-2</ul><br>MK:<ul><li>8003452",
        codigoBK: "PCRGASTRO",
        nota: "<ol><li><i>Campylobacter spp.<li><i>Clostridiodes difficile<li><i>E. coli Enteroinvasiva<li><i>Salmonella spp.<li><i>Shigella spp.<li>Yersinia enterocolitica</i><li>Norovirus G1<li>Norovirus G2<li>Astrovirus<li>Rotavirus<li>Adenovirus",
      },
      {
        tubo: "<img src='img/fdep32.png' height='32px'/>",
        examen: "Panel Gastroenteritis BACTERIANO - PARASITARIO - VIRAL (PCR-RT)",
        keywords: ['gastro15'],
        establecimiento: "<img src='img/bk.png' /> Barnafi",
        codigo: "Tecnigen:<ul><li>0303120-3</ul><br>MK:<ul><li>8003453",
        codigoBK: "GASTRO15",
        nota: `<ol><li><i>Campylobacter spp.<li><i>Clostridiodes difficile<li><i>E. coli Enteroinvasiva<li><i>Salmonella spp.<li><i>Shigella spp.
              <li>E. coli<li>Yersinia enterocolitica</i><li>Norovirus G1<li>Norovirus G2<li>Astrovirus<li>Rotavirus<li>Adenovirus<li>Sapovirus<li>E. histolytica
              <li>Crystosporidium spp.`,
      },
]
